Repository mely-apps/SudoMeLy, pull requests merged in 2023-08, with the labels that each got.

#38 Exchange Points
  src/commands/Admin/points/index.ts
  src/commands/Points/exchange.ts
  src/entities/User.ts
  src/utils/functions/embeds.ts
  src/utils/functions/string.ts
Labels: enhancement

#39 Open Sans font fixed
  src/commands/Points/rank.ts
  src/services/canvas/fonts/OpenSans-Bold.ttf
  src/services/canvas/fonts/OpenSans-BoldItalic.ttf
  src/services/canvas/fonts/OpenSans-ExtraBold.ttf
  src/services/canvas/fonts/OpenSans-ExtraBoldItalic.ttf
  src/services/canvas/fonts/OpenSans-Italic.ttf
  src/services/canvas/fonts/OpenSans-Light.ttf
  src/services/canvas/fonts/OpenSans-LightItalic.ttf
  src/services/canvas/fonts/OpenSans-Medium.ttf
  src/services/canvas/fonts/OpenSans-MediumItalic.ttf
  src/services/canvas/fonts/OpenSans-Regular.ttf
  src/services/canvas/fonts/OpenSans-SemiBold.ttf
  src/services/canvas/fonts/OpenSans-SemiBoldItalic.ttf
  src/services/canvas/index.ts
  src/services/index.ts
Labels: bug

#44 Fix: Reformat contribution guidelines
  .github/CONTRIBUTING.md
Labels: documentation

#46 ImageGenerator generic class
  .gitignore
  src/commands/Admin/points/export.ts
  src/services/imageGenerators/index.ts
  src/services/imageGenerators/leaderboard/assets/css/bootstrap.css
  src/services/imageGenerators/leaderboard/assets/css/icon.css
  src/services/imageGenerators/leaderboard/assets/css/reset.css
  src/services/imageGenerators/leaderboard/assets/css/styles.css
  src/services/imageGenerators/leaderboard/assets/img/bg.jpg
  src/services/imageGenerators/leaderboard/assets/img/medal.png
  src/services/imageGenerators/leaderboard/assets/js/main.js
  src/services/imageGenerators/leaderboard/index.html
  src/services/imageGenerators/leaderboard/index.ts
  src/services/imageGenerators/types.ts
  src/services/index.ts
  src/services/leaderboard/generate.ts
  src/services/leaderboard/index.ts
  src/utils/types/environment.d.ts
Labels: enhancement

#47 Point Manager
  src/commands/Admin/points/index.ts
  src/commands/Admin/points/scheduler.ts
  src/entities/User.ts
  src/events/custom/chatPoint.ts
  src/events/custom/threadArchive.ts
  src/events/custom/voicePoint.ts
  src/main.ts
  src/services/Database.ts
  src/services/PointManager.ts
  src/services/index.ts
  src/utils/functions/embeds.ts
Labels: enhancement

#56 Maintaining Mode
  src/commands/Owner/maintenance.ts
  src/events/custom/melyMemberJoined.ts
  src/events/custom/voicePoint.ts
  src/events/guildMemberRemove.ts
  src/events/messageCreate.ts
  src/events/ready.ts
  src/services/PointManager.ts
  src/services/Store.ts
  src/utils/functions/maintenance.ts
Labels: enhancement

#51 Fix: browser died
  src/services/imageGenerators/index.ts
Labels: bug

#58 Rank card
  src/commands/Points/point.ts
  src/commands/Points/rank.ts
  src/configs/index.ts
  src/configs/palettes.json
  src/entities/User.ts
  src/events/custom/rankUp.ts
  src/utils/functions/colors.ts
  src/utils/functions/number.ts
Labels: enhancement

#62 [Feature] Reset Rank
  src/commands/Admin/config/channels.ts
  src/commands/Admin/points/scheduler.ts
  src/commands/Points/point.ts
  src/entities/Guild.ts
  src/entities/RankHistory.ts
  src/entities/User.ts
  src/entities/index.ts
  src/events/custom/chatPoint.ts
  src/services/PointManager.ts
  src/utils/functions/number.ts
  src/utils/types/environment.d.ts
Labels: enhancement

#64 Kiếp đỏ đen #1
  src/commands/Admin/points/index.ts
  src/commands/Games/even_odd.ts
  src/commands/Points/exchange.ts
  src/commands/Points/transfer.ts
  src/entities/Transaction.ts
  src/entities/User.ts
  src/entities/index.ts
  src/events/threadCreate.ts
  src/events/threadDelete.ts
  src/services/Database.ts
  src/services/PointManager.ts
  src/utils/constants/enums.ts
  src/utils/constants/index.ts
Labels: enhancement
